#默认环境选项
spring:
  profiles:
    #默认环境配置名称
   active: test
#环境分割
---

#YML 文件描述
## 1.数据结构k-v结构
## 2、k与v 需要：“空格” 连接
## 3、YML配置文件有父子级关系 所以注意缩进位置
spring:
  profiles:
    active:
      on-profiles: prod
server:
  port: 80 #配置端口
  servlet: #web项目发布路径
    context-path: /  #/表示根目录
#定义dept属性值 yml文件默认支持UTF-8
dept:
  id: 100
  name: 财务部

#环境分割
---
spring:
  config:
    activate:
      on-profile: test

server:
  port: 8081
  servlet:
    context-path: /
dept:
  id: 100
  name: 集团本部