server:
  port: 8091
  servlet:
    context-path: /
spring:
  datasource:
    url: jdbc:mysql:///jtadmin?characterEncoding=utf-8&serverTime=Asia/Shanghai
    username: root
    password: root


#mybatis-plush配置
mybatis-plus:
  type-aliases-package: com.jt.pojo
  mapper-locations: classpath:/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.jt.mapper: debug
